In [11]:
# Create dataframe
import numpy as np

data=np.array([1, 3, 4, -5, 0, 3, 3, 2])

In [18]:
my_list=[1, 3, 4, -5, 0, 3, 3, 2]

In [19]:
my_list

[1, 3, 4, -5, 0, 3, 3, 2]

In [20]:
my_list.reshape(4,2)

AttributeError: 'list' object has no attribute 'reshape'

In [21]:
type(my_list),  type(data)

(list, numpy.ndarray)

In [12]:
data

array([ 1,  3,  4, -5,  0,  3,  3,  2])

In [13]:
data=data.reshape(4,2)
data

array([[ 1,  3],
       [ 4, -5],
       [ 0,  3],
       [ 3,  2]])

In [14]:
x=data[:, 0]
x

array([1, 4, 0, 3])

In [15]:
y=data[:, 1]
y

array([ 3, -5,  3,  2])

In [16]:
import matplotlib.pyplot as plt

In [17]:
plt.scatter(x,y)

In [22]:
data

array([[ 1,  3],
       [ 4, -5],
       [ 0,  3],
       [ 3,  2]])

In [23]:
import pandas as pd

my_data_frame=pd.DataFrame(data)

In [24]:
my_data_frame

0  1
0  1  3
1  4 -5
2  0  3
3  3  2

In [25]:
my_data_frame.columns=['x','y']

In [26]:
my_data_frame

x  y
0  1  3
1  4 -5
2  0  3
3  3  2

In [27]:
from sklearn.linear_model import LinearRegression

ModuleNotFoundError: No module named 'sklearn'

In [28]:
!pip install scikit-learn

  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/e8/dd/41bc4dfa519bc1a0617b68496120c472f1a1a5db264132d1530c43f059a8/scikit_learn-1.3.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/28/08/9dcdaa5aac4634e4c23af26d92121f7ce445c630efa0d3037881ae2407fb/joblib-1.3.1-py3-none-any.whl.metadata
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 9.2 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 15.1 MB/s eta 0:00:00


In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
LinearRegression?

Init signature:
LinearRegression(
    *,
    fit_intercept=True,
    copy_X=True,
    n_jobs=None,
    positive=False,
)
Docstring:     
Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, ..., wp)
to minimize the residual sum of squares between the observed targets in
the dataset, and the targets predicted by the linear approximation.

Parameters
----------
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (i.e. data is expected to be centered).

copy_X : bool, default=True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int, default=None
    The number of jobs to use for the computation. This will only provide
    speedup in case of sufficiently large problems, that is if firstly
    `n_targets > 1` and secondly `X` is sparse or if `positive` is set
    to `True`. ``None`` means 1 unless in a
    :obj:`

In [31]:
my_model=LinearRegression()

In [35]:
my_model?

Type:        LinearRegression
String form: LinearRegression()
File:        ~/.pyenv/versions/3.11.4/envs/2521_env/lib/python3.11/site-packages/sklearn/linear_model/_base.py
Docstring:  
Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, ..., wp)
to minimize the residual sum of squares between the observed targets in
the dataset, and the targets predicted by the linear approximation.

Parameters
----------
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (i.e. data is expected to be centered).

copy_X : bool, default=True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int, default=None
    The number of jobs to use for the computation. This will only provide
    speedup in case of sufficiently large problems, that is if firstly
    `n_targets > 1` and secondly `X` is sparse or if `positive` is set
    t

In [36]:
x, y

(array([1, 4, 0, 3]), array([ 3, -5,  3,  2]))

In [37]:
my_model.fit(x, y)

ValueError: Expected 2D array, got 1D array instead:
array=[1 4 0 3].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [45]:
my_model=my_model.fit(x.reshape(-1,1), y)
my_model

LinearRegression()

In [40]:
x.reshape(-1,1)

array([[1],
       [4],
       [0],
       [3]])

In [41]:
x.reshape(4,1)

array([[1],
       [4],
       [0],
       [3]])

In [46]:
my_model.coef_

array([-1.7])

In [47]:
my_model.intercept_

4.1499999999999995

In [48]:
my_model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'n_features_in_': 1,
 'coef_': array([-1.7]),
 'rank_': 1,
 'singular_': array([3.16227766]),
 'intercept_': 4.1499999999999995}

In [49]:
dir(my_model)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_decision_function',
 '_estimator_type',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_intercept',
 '_validate_data',
 '_validate_params',
 'coef_',
 'copy_X',
 'fit',
 'fit_intercept',
 'get_metadata_routing',
 'get_params',
 'intercept_',
 'n_features_in_',
 'n_jobs',
 'positive',
 

In [50]:
my_model.predict?

Signature: my_model.predict(X)
Docstring:
Predict using the linear model.

Parameters
----------
X : array-like or sparse matrix, shape (n_samples, n_features)
    Samples.

Returns
-------
C : array, shape (n_samples,)
    Returns predicted values.
File:      ~/.pyenv/versions/3.11.4/envs/2521_env/lib/python3.11/site-packages/sklearn/linear_model/_base.py
Type:      method

In [52]:
my_model.predict([[0]])

array([4.15])

In [53]:
my_model.predict([[0], [-3]])

array([4.15, 9.25])

In [55]:
x

array([1, 4, 0, 3])

In [56]:
my_data_frame

x  y
0  1  3
1  4 -5
2  0  3
3  3  2

In [58]:
my_data_frame['x']

0    1
1    4
2    0
3    3
Name: x, dtype: int64

In [60]:
my_data_frame.iloc[1]

x    4
y   -5
Name: 1, dtype: int64

In [61]:
my_data_frame.index

RangeIndex(start=0, stop=4, step=1)

In [62]:
my_data_frame.index=['A', 'B', 'C', 'D']

In [63]:
my_data_frame

x  y
A  1  3
B  4 -5
C  0  3
D  3  2

In [64]:
my_data_frame['B']

KeyError: 'B'

In [65]:
my_data_frame.loc['B']

x    4
y   -5
Name: B, dtype: int64

In [66]:
my_data_frame.iloc[1]

x    4
y   -5
Name: B, dtype: int64