### Pandas continued

See chapter 5 of Wes McKinney Python for Data Analysis

https://wesmckinney.com/book/pandas-basics.html#pandas_construction


### DataFrame

A DataFrame is like an excel spreadsheet, i.e. 2D object

- column names are in a list called `columns`
- rows or names of rows are in a list called `index` (not rows)
- if you construct a DataFrame from a dictionary, the **keys** of the dictionary become **column** names, not row names 


In [164]:
import pandas as pd
import numpy as np

matrix=np.arange(12).reshape(3,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [165]:
df=pd.DataFrame(matrix, columns=['A', 'B', 'C', 'D'], index=[2, 'row2', 'row3'])

In [166]:
df

A  B   C   D
2     0  1   2   3
row2  4  5   6   7
row3  8  9  10  11

In [167]:
df['A']

2       0
row2    4
row3    8
Name: A, dtype: int64

In [169]:
df['row1'] #gives error, must use loc and iloc for rows!

KeyError: 'row1'

In [ ]:
df

A  B   C   D
2     0  1   2   3
row2  4  5   6   7
row3  8  9  10  11

In [ ]:
df.index

Index([2, 'row2', 'row3'], dtype='object')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.loc[2]

A    0
B    1
C    2
D    3
Name: 2, dtype: int64

In [ ]:
df.iloc[0]  #iloc is `integer locate', python counting starts at 0

A    0
B    1
C    2
D    3
Name: 2, dtype: int64

### Deleting a row or column:

use `.drop(column=[])` for dropping columns 

or `.drop(index=[])` for dropping rows (index means rows)

In [ ]:
df

A  B   C   D
2     0  1   2   3
row2  4  5   6   7
row3  8  9  10  11

In [ ]:
df.drop(columns=['A'])

B   C   D
2     1   2   3
row2  5   6   7
row3  9  10  11

In [ ]:
df

A  B   C   D
2     0  1   2   3
row2  4  5   6   7
row3  8  9  10  11

Notice above that column A has not been deleted from `df` because the `drop` operation first creates a **copy** of `df`, from which it deletes the column, and it does not act on `df`. But you want it to delete the column in your original DataFrame, use `inplace=True` as below:

In [ ]:
df.drop(columns=['A'], inplace=True)

In [ ]:
df

B   C   D
2     1   2   3
row2  5   6   7
row3  9  10  11

In [ ]:
# delete row2
df.drop(index=['row2'])

B   C   D
2     1   2   3
row3  9  10  11

### Replacing a column

In [ ]:
df

B   C   D
2     1   2   3
row2  5   6   7
row3  9  10  11

In [ ]:
df['B']=[2,3, 4]

In [ ]:
df

B   C   D
2     2   2   3
row2  3   6   7
row3  4  10  11

###  Replacing a row

In [ ]:
df.loc['row2']=[20,20,20]

In [ ]:
df

B   C   D
2      2   2   3
row2  20  20  20
row3   4  10  11

# Filtering based on value of a column

Suppose we want all rows where value in column C is >5.

First create a true-false 'mask':

In [ ]:
df

B   C   D
2      2   2   3
row2  20  20  20
row3   4  10  11

In [ ]:
df['C']>5

2       False
row2     True
row3     True
Name: C, dtype: bool

In [ ]:
df[df['C']>5]

B   C   D
row2  20  20  20
row3   4  10  11

In [ ]:
mask=df['C']>5
df[mask]

B   C   D
row2  20  20  20
row3   4  10  11

In [ ]:
df

B   C   D
2      2   2   3
row2  20  20  20
row3   4  10  11

In [ ]:
mask2=df['B']<=4

In [ ]:
mask2

2        True
row2    False
row3     True
Name: B, dtype: bool

In [ ]:
df[mask2]

B   C   D
2     2   2   3
row3  4  10  11

Adding two dataframes with possibly some different columns or indexes is possible, will just introduce `NaN`s in appropriate places. This example is copied from McKinney section 5.2:

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
   .....:                    index=["Ohio", "Texas", "Colorado"])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
   .....:                    index=["Utah", "Ohio", "Texas", "Oregon"])


In [ ]:
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [ ]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Applying functions to entries of a data frame

In [ ]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [ ]:
np.square(df1)  #vectorized numpy operations accept dataframes as input

b     c     d
Ohio       0.0   1.0   4.0
Texas      9.0  16.0  25.0
Colorado  36.0  49.0  64.0

### Apply a function to rows or columns

syntax

`.apply`

`<dataframe>.apply(function, axis=)`

In [ ]:
def my_function(x):
    return x**2

df=df.apply(my_function)
df

B       C       D
2         16      16      81
row2  160000  160000  160000
row3     256   10000   14641

In [ ]:
df

B       C       D
2         16      16      81
row2  160000  160000  160000
row3     256   10000   14641

In [ ]:
#replace just column B with it entries squares
df['B']=df['B'].apply(my_function)

In [ ]:
df

B       C       D
2             256      16      81
row2  25600000000  160000  160000
row3        65536   10000   14641

In [ ]:
df.loc[2]=df.loc[2].apply(my_function)

In [ ]:
df

B       C       D
2           65536     256    6561
row2  25600000000  160000  160000
row3        65536   10000   14641

In [ ]:
df.iloc[2]=df.iloc[2].apply(my_function)

In [ ]:
df

B          C          D
2           65536        256       6561
row2  25600000000     160000     160000
row3   4294967296  100000000  214358881

### Sorting

Can sort index, but I think more common is to sort the values:

In [ ]:
df

B          C          D
2           65536        256       6561
row2  25600000000     160000     160000
row3   4294967296  100000000  214358881

In [ ]:
df.sort_values(by=['B'])

B          C          D
2           65536        256       6561
row3   4294967296  100000000  214358881
row2  25600000000     160000     160000

In [ ]:
df

B          C          D
2           65536        256       6561
row2  25600000000     160000     160000
row3   4294967296  100000000  214358881

In [ ]:
df.sort_values(by=['D','B'])

B          C          D
2           65536        256       6561
row2  25600000000     160000     160000
row3   4294967296  100000000  214358881

In [ ]:
df

B          C          D
2           65536        256       6561
row2  25600000000     160000     160000
row3   4294967296  100000000  214358881

[rows, columns]

In [ ]:
df.sum(axis=0)

B    29895032832
C      100160256
D      214525442
dtype: int64

### Axis, again

Yesterday I said (correctly)

### axis=0 means varying rows, keeping column fixed

I wrote 
### axis=0 means columns
but I should have written more precisely
### axis=0 means (operation is applied to) columns

and while correct, the usage in Pandas/McKinney is that axis means direction 

`axis=0` is `axis="rows"`
because if you say sum in the direction of rows axis, you are summing up to columns.

And
`axis=1` is synonymous with `axis="columns"`
since doing a sum along the direction of the columns axis is summing each row.

Very confusing, I'm sorry.


In [ ]:
df

B          C          D
2           65536        256       6561
row2  25600000000     160000     160000
row3   4294967296  100000000  214358881

In [ ]:

df.sum(axis=0)

B    29895032832
C      100160256
D      214525442
dtype: int64

In [ ]:
df.sum(axis='index')

B    29895032832
C      100160256
D      214525442
dtype: int64

In [ ]:
#the following command sums the ROWS
df.sum(axis='columns')

2             72353
row2    25600320000
row3     4609326177
dtype: int64

###  concat

pd.concat?

In [ ]:
pd.concat?

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[HashableT, NDFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index',

In [ ]:
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [ ]:
pd.concat([df1, df2])  #default axis=0 i.e. rows

b    c     d     e
Ohio      0.0  1.0   2.0   NaN
Texas     3.0  4.0   5.0   NaN
Colorado  6.0  7.0   8.0   NaN
Utah      0.0  NaN   1.0   2.0
Ohio      3.0  NaN   4.0   5.0
Texas     6.0  NaN   7.0   8.0
Oregon    9.0  NaN  10.0  11.0

In [ ]:
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [ ]:
pd.concat([df1, df2], axis=1)

b    c    d    b     d     e
Ohio      0.0  1.0  2.0  3.0   4.0   5.0
Texas     3.0  4.0  5.0  6.0   7.0   8.0
Colorado  6.0  7.0  8.0  NaN   NaN   NaN
Utah      NaN  NaN  NaN  0.0   1.0   2.0
Oregon    NaN  NaN  NaN  9.0  10.0  11.0

In [ ]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

## McKinney Chapter 10 Group operations
### groupby
### split-apply-combine paradigm

 - split the rows
 - apply a function
 - combine the results

https://wesmckinney.com/book/data-aggregation.html?q=groupby#groupby_fundamentals

In [ ]:
# example from McKinney Chapter 10

df = pd.DataFrame({"key1" : ["a", "a", None, "b", "b", "a", None],
                 "key2" : pd.Series([1, 2, 1, 2, 1, None, 1],
                                     dtype="Int64"),
                 "data1" : np.random.standard_normal(7),
                  "data2" : np.random.standard_normal(7)})



In [ ]:
df

key1  key2     data1     data2
0     a     1 -0.771237 -0.684660
1     a     2  0.388218  0.313966
2  None     1 -0.072378  0.668783
3     b     2 -0.294783 -1.224849
4     b     1 -0.028292 -1.321189
5     a  <NA>  0.891031 -0.287722
6  None     1 -0.008635  0.096108

In [ ]:
grouped = df["data1"].groupby(df["key1"])  #split by key1 value
grouped


In [ ]:
grouped.sum()  #apply the sum function

key1
a    0.508013
b   -0.323075
Name: data1, dtype: float64

# Week 3 video
HW: Go through one of the examples in Chapter 13
and make an 5-10 min instructional video

https://wesmckinney.com/book/data-analysis-examples

Github Datasets:

https://github.com/wesm/pydata-book

Download to your local device, know where you save it


In [ ]:
import json

In [ ]:
db = json.load(open("database.json"))

In [ ]:
!ls  #windows: !dir

2521_Syllabus.md                chapter4notes.ipynb
Exercise112.py                  chapter5notes.ipynb
PythonNotesForProfessionals.pdf chapter5notes_day2.ipynb
README.md                       chapter7notes.ipynb
__pycache__                     chapter8notes.ipynb
chapter10notes.ipynb            database.json
chapter10notes_day2.ipynb       my_figure.pdf
chapter1notes.ipynb             my_filename
chapter2notes.ipynb             test.csv
chapter3notes.ipynb             test1.txt
chapter3notes_day2.ipynb        text-to-image.ipynb


In [ ]:
len(db)

6636

In [163]:
db[0]  # this is a dictionary

{'id': 1008,
 'description': 'Cheese, caraway',
 'tags': [],
 'manufacturer': '',
 'group': 'Dairy and Egg Products',
 'portions': [{'amount': 1, 'unit': 'oz', 'grams': 28.35}],
 'nutrients': [{'value': 25.18,
   'units': 'g',
   'description': 'Protein',
   'group': 'Composition'},
  {'value': 29.2,
   'units': 'g',
   'description': 'Total lipid (fat)',
   'group': 'Composition'},
  {'value': 3.06,
   'units': 'g',
   'description': 'Carbohydrate, by difference',
   'group': 'Composition'},
  {'value': 3.28, 'units': 'g', 'description': 'Ash', 'group': 'Other'},
  {'value': 376.0,
   'units': 'kcal',
   'description': 'Energy',
   'group': 'Energy'},
  {'value': 39.28,
   'units': 'g',
   'description': 'Water',
   'group': 'Composition'},
  {'value': 1573.0, 'units': 'kJ', 'description': 'Energy', 'group': 'Energy'},
  {'value': 0.0,
   'units': 'g',
   'description': 'Fiber, total dietary',
   'group': 'Composition'},
  {'value': 673.0,
   'units': 'mg',
   'description': 'Calcium,